service: github-copilot-lex-bot-deployment-v2

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

custom:
  lex:
    botName: GitHubCopilotLexBotv2
    botAlias: v1
    botDescription: Bot to order flowers
    intents: ${file(bot-definition.json)}

resources:
  Resources:
    LexBot:
      Type: AWS::Lex::Bot
      Properties: ${self:custom.lex}